### ISSUE TITLE
possible to run on wsl?

### ISSUE THREAD

**Issue by surajsharma** [androidvirtualpen/virtualpen#6]
on wsl the host application fails to list my device, wondering if it is at all passible

![image](https://github.com/androidvirtualpen/virtualpen/assets/5298624/4b214a28-bd53-414a-bb60-39b9ed44584a)

**Comment by thebashforkbomber** [comment]
No. Never. WSL does not expose so much APIs to WSL.

**Comment by Mathieu-Beliveau** [comment]
Hi to you both! First and foremost, apologies for the delay. Indeed, I highly doubt that the specific kernel module the application is using under linux will be available on WSL. That being said, if spare time allows, I will eventually look on how to emulate a pen under native Windows system and write something for it. It would really be nice if this application can have a windows user base. Thanks for your interest and feedback!
